### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by brry** [brry/berryFunctions#7]
moved out of NEWS file

- [ ] textField: support srt. Enable positioning with xy.coords as in legend. expr=F if labels contain expression. Adjust adj parameter based on pos and offset: if(!is.null(pos)), I want the field to still be drawn with adj, but have it based on pos
- [ ] colPoints: add argument zlog=TRUE
- [ ] linLogHist + linLogTrans: check test warnings and remove reason (rainbow2!)
- [ ] monthAxis: remove warning to timeAxis for short time ranges + change behaviour?
- [ ] lsc: better example dataset, optim problems
- [ ] tryStack: if silent=TRUE, put all warnings and messages into final output (not just last one)
- [ ] tryStack: example warning with log(-1:6) for non-repeated call stack
- [ ] tryStack: mapply, do.call etc put function name in next element
- [ ] getColumn: consider renaming argument x
